### ISSUE TITLE
Prioritized list of Regent features for HTR

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1032]
This is mostly a bookkeeping issue, to help us track the current set of prioritized Regent issues for HTR. My understanding is that these issues are currently (in order of priority):

 - [x] #637 separate compilation
 - [x] #958 error when passing a large struct to a CUDA task in Regent
 - [ ] #878 compact sparse instances
 - [ ] #995 deferred buffers
 - [ ] #789 privileges on regions in fspaces

**Comment by mariodirenzo** [comment]
I think that HTR would also benefit from the solution of #873 and #694.
They are not critical so they should have the lowest priority.

**Comment by streichler** [comment]
Pinging here too: #1154 has a proposed fix that I need somebody to test out

**Comment by mariodirenzo** [comment]
@elliottslaughter, could you please insert #1276 in the Regent section with high priority?

**Comment by mariodirenzo** [comment]
@elliottslaughter, could you add #1292 to the Realm section with low priority?

**Comment by mariodirenzo** [comment]
@elliottslaughter, could you add #1386, #1387, and #1388 to the Realm (first two) and Legion (third issue) sections?
All these issues have low priority.
Thanks

**Comment by mariodirenzo** [comment]
@elliottslaughter, could you add #1364 to the Realm issues with priority just below #521?

**Comment by mariodirenzo** [comment]
@elliottslaughter, could you please add #1420 to the legion section?

**Comment by mariodirenzo** [comment]
@elliottslaughter, sorry for asking to add issues so frequently. Could you add #1262 to the Realm section above 1364?
