### ISSUE TITLE
DG-Legion: tracking issue for needed improvements

### ISSUE THREAD

**Issue by bandokihiro** [StanfordLegion/legion#1046]
This is an issue for me and legion developers to keep track of issues and needed improvements for the DG-Legion application. This post will be updated as issues get fixed or new desired features show up.

**Porting the code to GPUs using Kokkos**
- [ ] debug slow copies when using multiple GPUs
- [ ] test scaling with possible required use of sparse instances to reduce memory usage
- [ ] fix linkage with kokkos-kernels and third-party libraries (e.g. mkl) in OpenMP mode (see issue #978)

**Comment by bandokihiro** [comment]
Closing this since this project took a different direction and I am using another way for tracking needed additions to Legion.
