### ISSUE TITLE
Deppart Merge TODO

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#294]
- [x] Fix Issue #277 (sean) 
- [x] Delete old Realm index space code and rename all 'Z' types (both)
- [x] Proper support for deferral of Realm dependent partitioning operations (sean)
- [x] Instance and dependent partitioning profiling responses (sean)
- [x] Gitlab CI passing (both)
- [x] Deal with timeouts on Travis and Gitlab CI (both)
- [x] Fix issue #293 (sean)
- [x] Check and (as necessary) resolve performance regressions https://stanfordlegion.github.io/perf-frontend/perf_chart.html
- [x] Fix 1-D rectangle coalescing for circuit_dp.rg
- [x] Decide whether issue #296 must be fixed before the merge
- [x] NaNs in miniaero (both)
- [x] slowdown for multi-node circuit (both)
---
- ~~Compaction?~~

**Comment by elliottslaughter** [comment]
I added checkboxes. (Syntax is `- [ ]` for unchecked and `- [X]` for checked.) Yay, shiny.

**Comment by lightsighter** [comment]
@streichler Use the -DREALM_PROFILING_FIX macro to test the fixes for the profiling responses.  A crash indicates too many responses and a hang indicates too few.

**Comment by lightsighter** [comment]
@streichler Here are instructions to reproduce the rectangle coalescing issue:
CC_FLAGS=-DPERFECT_REALM_COALESCING ./install.py
./regent.py examples/circuit_dp.rg

You should see this error deterministically: assertion failed: in_ptr not local?

Here is the relevant piece of code for IndexIterator that makes the difference: https://github.com/StanfordLegion/legion/blob/deppart/runtime/legion/legion.inl#L3662-L3713

**Comment by lightsighter** [comment]
The cause of the performance regressions has been tracked down. It has to do with the disabling of auto-vectorization in Regent.  See issue #296 for more details.  We need to decide whether we want the fix for that issue to be a blocking problem for the deppart merge.

**Comment by lightsighter** [comment]
Issue #296 may also be contributing to our timeouts on both travis and gitlab CI.  However, longer compile times are also a likely factor.

**Comment by lightsighter** [comment]
We decided not to fix #296 before the merge. It will be a priority for @magnatelee when he returns from vacation.

**Comment by lightsighter** [comment]
Closing this issue now that dependent partitioning has been merged.
