### ISSUE TITLE
ECP Milestone (ST-PR-10-1320)     

### ISSUE THREAD

**Issue by pmccormick** [StanfordLegion/legion#650]
Due: 2020-01-31 

- [x] Gain access to, learn and understand the CANDLE training network(s) that would benefit from improved execution time and utilizing large system scales. Gather initial performance characteristics of CANDLE's use cases.

- [ ] Prototype and harden efforts to support translation of TensorFlow and/or PyTorch programs to Legion (additional DL/ML programming systems can be explored if there is a need within ECP but our first efforts are focused on CANDLE use cases).

- [ ] Explore implications of new hardware and software environments on this workload OpenCL, ROCm, and other emerging possibilities. Consideration will be given to platform portability as well as performance, stability, feature set and code refactoring impacts. 

- [ ] Implement necessary Realm functionality using selected API.

- [ ] Completion Criteria:: Documentation covering progress towards improving training performance and scalability for ECP DL/ML applications, general Legion improvements, and feature set impacts for supporting ECP system architectures and accelerators.  Details will include software contributions and release(s).

**Comment by elliottslaughter** [comment]
@pmccormick Is this finished? The release was here: https://github.com/StanfordLegion/legion/releases/tag/legion-19.12.0

**Comment by pmccormick** [comment]
Mostly, although quarterly software releases are not really what ECP wants to see anymore (but we can use it as part of the storyline).  We need to document the pieces in the checklist to make them happy.  @alexaiken had promised he was going to take care of this one...  ;-)    I would not close it until we submit the ECP report.

**Comment by elliottslaughter** [comment]
Maybe we should move this into the 20.03 milestone then, since it (by definition) can't be included in the 12.10 release?
