### ISSUE TITLE
ECP Milestone (ST-PR-10-1350)

### ISSUE THREAD

**Issue by pmccormick** [StanfordLegion/legion#651]
Due:      2020-05-31 

- [ ] Conduct correctness, performance and scaling tests of Legion versions of the training network(s). Debug and improve as necessary. Potentially revisit the need for additional interfaces beyond PyTorch and TensorFlow.

- [ ]  Continued implementation and testing of Realm functionality for target accelerator API and hardware nuances.

- [ ] Test, evaluate and debug capabilities. Tune node-level performance – scaling will potentially not be available given limited deployment of any selected GPUs within the DOE.

- [ ] Software release.
