### ISSUE TITLE
ECP Milestone (ST-PR-10-1380)

### ISSUE THREAD

**Issue by pmccormick** [StanfordLegion/legion#652]
Due: 2020-09-30 

- [ ] Implement, release and integrate for testing of any additional benchmarks to help identify and track performance bottlenecks.

- [ ] Explore additional app-centric issues (bugs and performance issues) and understand and address impacts based on complexities not possible to capture with lower-level benchmarks.

- [ ] The Legion project currently has a CI testing system that is used internally for validating software updates.  Extensions to this system are needed to test at larger scale.  We will either undertake this within the project or explore integration with an ECP-wide CI system when that becomes available.

Completion Criteria: 

- [ ] Documented details of identified overheads, resulting fixes and resulting improvements in performance.

- [ ] Software releases with corresponding performance issues addressed.

- [ ] Software releases with bug fixes.

- [ ] Improved testing infrastructure (including tracking performance characteristics where and when possible).

**Comment by elliottslaughter** [comment]
Whatever we did or did not do, this is project is long since over.
